<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8e74d19e-bb16-4ac7-9d7a-88d3c20c7464</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StrictDocOslcRm\StrictDocOslcRm.csproj" />
  </ItemGroup>
</Project>
